/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ENameRouteRouteImport } from './routes/e/$name/route'
import { Route as PKeyRouteRouteImport } from './routes/p/$key/route'
import { Route as WKeyRouteRouteImport } from './routes/w/$key/route'
import { Route as ENameIndexRouteImport } from './routes/e/$name/index'
import { Route as ENameLedgerRouteImport } from './routes/e/$name/ledger'
import { Route as PKeyIndexRouteImport } from './routes/p/$key/index'
import { Route as PKeyLedgerRouteImport } from './routes/p/$key/ledger'
import { Route as WKeyIndexRouteImport } from './routes/w/$key/index'
import { Route as WKeyArchiveRouteImport } from './routes/w/$key/archive'
import { Route as WKeyContextRouteImport } from './routes/w/$key/context'
import { Route as WKeyLedgerRouteImport } from './routes/w/$key/ledger'
import { Route as WKeyFileSplatRouteImport } from './routes/w/$key/file/$'
import { Route as WKeyItemIdRouteImport } from './routes/w/$key/item/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ENameRouteRoute = ENameRouteRouteImport.update({
  id: '/e/$name',
  path: '/e/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PKeyRouteRoute = PKeyRouteRouteImport.update({
  id: '/p/$key',
  path: '/p/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const WKeyRouteRoute = WKeyRouteRouteImport.update({
  id: '/w/$key',
  path: '/w/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ENameIndexRoute = ENameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ENameRouteRoute,
} as any)
const ENameLedgerRoute = ENameLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => ENameRouteRoute,
} as any)
const PKeyIndexRoute = PKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PKeyRouteRoute,
} as any)
const PKeyLedgerRoute = PKeyLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => PKeyRouteRoute,
} as any)
const WKeyIndexRoute = WKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyArchiveRoute = WKeyArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyContextRoute = WKeyContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyLedgerRoute = WKeyLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyFileSplatRoute = WKeyFileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyItemIdRoute = WKeyItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => WKeyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e/$name': typeof ENameRouteRouteWithChildren
  '/p/$key': typeof PKeyRouteRouteWithChildren
  '/w/$key': typeof WKeyRouteRouteWithChildren
  '/e/$name/ledger': typeof ENameLedgerRoute
  '/p/$key/ledger': typeof PKeyLedgerRoute
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/e/$name/': typeof ENameIndexRoute
  '/p/$key/': typeof PKeyIndexRoute
  '/w/$key/': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e/$name/ledger': typeof ENameLedgerRoute
  '/p/$key/ledger': typeof PKeyLedgerRoute
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/e/$name': typeof ENameIndexRoute
  '/p/$key': typeof PKeyIndexRoute
  '/w/$key': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e/$name': typeof ENameRouteRouteWithChildren
  '/p/$key': typeof PKeyRouteRouteWithChildren
  '/w/$key': typeof WKeyRouteRouteWithChildren
  '/e/$name/ledger': typeof ENameLedgerRoute
  '/p/$key/ledger': typeof PKeyLedgerRoute
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/e/$name/': typeof ENameIndexRoute
  '/p/$key/': typeof PKeyIndexRoute
  '/w/$key/': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e/$name'
    | '/p/$key'
    | '/w/$key'
    | '/e/$name/ledger'
    | '/p/$key/ledger'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/e/$name/'
    | '/p/$key/'
    | '/w/$key/'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e/$name/ledger'
    | '/p/$key/ledger'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/e/$name'
    | '/p/$key'
    | '/w/$key'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  id:
    | '__root__'
    | '/'
    | '/e/$name'
    | '/p/$key'
    | '/w/$key'
    | '/e/$name/ledger'
    | '/p/$key/ledger'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/e/$name/'
    | '/p/$key/'
    | '/w/$key/'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ENameRouteRoute: typeof ENameRouteRouteWithChildren
  PKeyRouteRoute: typeof PKeyRouteRouteWithChildren
  WKeyRouteRoute: typeof WKeyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$name': {
      id: '/e/$name'
      path: '/e/$name'
      fullPath: '/e/$name'
      preLoaderRoute: typeof ENameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$key': {
      id: '/p/$key'
      path: '/p/$key'
      fullPath: '/p/$key'
      preLoaderRoute: typeof PKeyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$key': {
      id: '/w/$key'
      path: '/w/$key'
      fullPath: '/w/$key'
      preLoaderRoute: typeof WKeyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$name/': {
      id: '/e/$name/'
      path: '/'
      fullPath: '/e/$name/'
      preLoaderRoute: typeof ENameIndexRouteImport
      parentRoute: typeof ENameRouteRoute
    }
    '/e/$name/ledger': {
      id: '/e/$name/ledger'
      path: '/ledger'
      fullPath: '/e/$name/ledger'
      preLoaderRoute: typeof ENameLedgerRouteImport
      parentRoute: typeof ENameRouteRoute
    }
    '/p/$key/': {
      id: '/p/$key/'
      path: '/'
      fullPath: '/p/$key/'
      preLoaderRoute: typeof PKeyIndexRouteImport
      parentRoute: typeof PKeyRouteRoute
    }
    '/p/$key/ledger': {
      id: '/p/$key/ledger'
      path: '/ledger'
      fullPath: '/p/$key/ledger'
      preLoaderRoute: typeof PKeyLedgerRouteImport
      parentRoute: typeof PKeyRouteRoute
    }
    '/w/$key/': {
      id: '/w/$key/'
      path: '/'
      fullPath: '/w/$key/'
      preLoaderRoute: typeof WKeyIndexRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/archive': {
      id: '/w/$key/archive'
      path: '/archive'
      fullPath: '/w/$key/archive'
      preLoaderRoute: typeof WKeyArchiveRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/context': {
      id: '/w/$key/context'
      path: '/context'
      fullPath: '/w/$key/context'
      preLoaderRoute: typeof WKeyContextRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/ledger': {
      id: '/w/$key/ledger'
      path: '/ledger'
      fullPath: '/w/$key/ledger'
      preLoaderRoute: typeof WKeyLedgerRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/file/$': {
      id: '/w/$key/file/$'
      path: '/file/$'
      fullPath: '/w/$key/file/$'
      preLoaderRoute: typeof WKeyFileSplatRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/item/$id': {
      id: '/w/$key/item/$id'
      path: '/item/$id'
      fullPath: '/w/$key/item/$id'
      preLoaderRoute: typeof WKeyItemIdRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
  }
}

interface ENameRouteRouteChildren {
  ENameLedgerRoute: typeof ENameLedgerRoute
  ENameIndexRoute: typeof ENameIndexRoute
}

const ENameRouteRouteChildren: ENameRouteRouteChildren = {
  ENameLedgerRoute: ENameLedgerRoute,
  ENameIndexRoute: ENameIndexRoute,
}

const ENameRouteRouteWithChildren = ENameRouteRoute._addFileChildren(
  ENameRouteRouteChildren,
)

interface PKeyRouteRouteChildren {
  PKeyLedgerRoute: typeof PKeyLedgerRoute
  PKeyIndexRoute: typeof PKeyIndexRoute
}

const PKeyRouteRouteChildren: PKeyRouteRouteChildren = {
  PKeyLedgerRoute: PKeyLedgerRoute,
  PKeyIndexRoute: PKeyIndexRoute,
}

const PKeyRouteRouteWithChildren = PKeyRouteRoute._addFileChildren(
  PKeyRouteRouteChildren,
)

interface WKeyRouteRouteChildren {
  WKeyArchiveRoute: typeof WKeyArchiveRoute
  WKeyContextRoute: typeof WKeyContextRoute
  WKeyLedgerRoute: typeof WKeyLedgerRoute
  WKeyIndexRoute: typeof WKeyIndexRoute
  WKeyFileSplatRoute: typeof WKeyFileSplatRoute
  WKeyItemIdRoute: typeof WKeyItemIdRoute
}

const WKeyRouteRouteChildren: WKeyRouteRouteChildren = {
  WKeyArchiveRoute: WKeyArchiveRoute,
  WKeyContextRoute: WKeyContextRoute,
  WKeyLedgerRoute: WKeyLedgerRoute,
  WKeyIndexRoute: WKeyIndexRoute,
  WKeyFileSplatRoute: WKeyFileSplatRoute,
  WKeyItemIdRoute: WKeyItemIdRoute,
}

const WKeyRouteRouteWithChildren = WKeyRouteRoute._addFileChildren(
  WKeyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ENameRouteRoute: ENameRouteRouteWithChildren,
  PKeyRouteRoute: PKeyRouteRouteWithChildren,
  WKeyRouteRoute: WKeyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
