/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WKeyRouteRouteImport } from './routes/w/$key/route'
import { Route as WKeyIndexRouteImport } from './routes/w/$key/index'
import { Route as WKeyArchiveRouteImport } from './routes/w/$key/archive'
import { Route as WKeyContextRouteImport } from './routes/w/$key/context'
import { Route as WKeyLedgerRouteImport } from './routes/w/$key/ledger'
import { Route as WKeyFileSplatRouteImport } from './routes/w/$key/file/$'
import { Route as WKeyItemIdRouteImport } from './routes/w/$key/item/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WKeyRouteRoute = WKeyRouteRouteImport.update({
  id: '/w/$key',
  path: '/w/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const WKeyIndexRoute = WKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyArchiveRoute = WKeyArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyContextRoute = WKeyContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyLedgerRoute = WKeyLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyFileSplatRoute = WKeyFileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => WKeyRouteRoute,
} as any)
const WKeyItemIdRoute = WKeyItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => WKeyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$key': typeof WKeyRouteRouteWithChildren
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/w/$key/': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/w/$key': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$key': typeof WKeyRouteRouteWithChildren
  '/w/$key/archive': typeof WKeyArchiveRoute
  '/w/$key/context': typeof WKeyContextRoute
  '/w/$key/ledger': typeof WKeyLedgerRoute
  '/w/$key/': typeof WKeyIndexRoute
  '/w/$key/file/$': typeof WKeyFileSplatRoute
  '/w/$key/item/$id': typeof WKeyItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$key'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/w/$key/'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/w/$key'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  id:
    | '__root__'
    | '/'
    | '/w/$key'
    | '/w/$key/archive'
    | '/w/$key/context'
    | '/w/$key/ledger'
    | '/w/$key/'
    | '/w/$key/file/$'
    | '/w/$key/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WKeyRouteRoute: typeof WKeyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$key': {
      id: '/w/$key'
      path: '/w/$key'
      fullPath: '/w/$key'
      preLoaderRoute: typeof WKeyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$key/': {
      id: '/w/$key/'
      path: '/'
      fullPath: '/w/$key/'
      preLoaderRoute: typeof WKeyIndexRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/archive': {
      id: '/w/$key/archive'
      path: '/archive'
      fullPath: '/w/$key/archive'
      preLoaderRoute: typeof WKeyArchiveRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/context': {
      id: '/w/$key/context'
      path: '/context'
      fullPath: '/w/$key/context'
      preLoaderRoute: typeof WKeyContextRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/ledger': {
      id: '/w/$key/ledger'
      path: '/ledger'
      fullPath: '/w/$key/ledger'
      preLoaderRoute: typeof WKeyLedgerRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/file/$': {
      id: '/w/$key/file/$'
      path: '/file/$'
      fullPath: '/w/$key/file/$'
      preLoaderRoute: typeof WKeyFileSplatRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
    '/w/$key/item/$id': {
      id: '/w/$key/item/$id'
      path: '/item/$id'
      fullPath: '/w/$key/item/$id'
      preLoaderRoute: typeof WKeyItemIdRouteImport
      parentRoute: typeof WKeyRouteRoute
    }
  }
}

interface WKeyRouteRouteChildren {
  WKeyArchiveRoute: typeof WKeyArchiveRoute
  WKeyContextRoute: typeof WKeyContextRoute
  WKeyLedgerRoute: typeof WKeyLedgerRoute
  WKeyIndexRoute: typeof WKeyIndexRoute
  WKeyFileSplatRoute: typeof WKeyFileSplatRoute
  WKeyItemIdRoute: typeof WKeyItemIdRoute
}

const WKeyRouteRouteChildren: WKeyRouteRouteChildren = {
  WKeyArchiveRoute: WKeyArchiveRoute,
  WKeyContextRoute: WKeyContextRoute,
  WKeyLedgerRoute: WKeyLedgerRoute,
  WKeyIndexRoute: WKeyIndexRoute,
  WKeyFileSplatRoute: WKeyFileSplatRoute,
  WKeyItemIdRoute: WKeyItemIdRoute,
}

const WKeyRouteRouteWithChildren = WKeyRouteRoute._addFileChildren(
  WKeyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WKeyRouteRoute: WKeyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
